---
abstract: 'Gruntmaster 6000 Online Judge -- GUI database editor'
author:
  - 'Marius Gavrilescu <marius@ieval.ro>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Gruntmaster-GUI
no_index:
  directory:
    - t
    - inc
requires:
  Gruntmaster::Data: '0'
  Sub::Name: '0'
  Try::Tiny: '0'
  Wx: '0'
  Wx::Event: '0'
  perl: '5.014000'
resources:
  repository: https://git.ieval.ro/?p=gruntmaster-gui.git
version: 5999.000_001
